### ISSUE TITLE
Incompatibility with Advanced Vehicle Options

### ISSUE THREAD

**Issue by benzoll37** [dymanoid/MoreVehicles#1]
I have taken an old city of 411k cims, played 1 hour and adapted it to v 1.12. Then I put your mod, and vehicles pass limit without problem: 18k, 20k, 23k.
I have continued playing and I only observe an anomaly: cargo train disappears, there are no trains of merchandise.
Ship cargo go up and down in number, but ok

Continued testing city. Now it has 480k cims.

Edit.- The feeling is that trucks stop going to the loading station, and therefore there are no trains.

**Comment by benzoll37** [comment]
With cargo port trucks and ships go up and down, but it ends up recovering. I have one.
I deleted a cargo station and put a new one: definitely the trucks that go to it decrease in large numbers, and no cargo train arrives importing goods. They do not come out either.
I have 4 station cargo in 4 industrial zones, and only for interurban traffic of merchandise trains should work.

Edit.- I have continued the test, it seems clear: cargo trains do not work. When city need more transportation importing/exporting, cargo ship and trucks are increased.

**Comment by dymanoid** [comment]
Could you please share your save file? I'm having no problems with my test setup. There is probably something special to consider.

**Comment by benzoll37** [comment]
Wait, I just realized, might conflict with AVO mod. _Cargo trains_ are split and are not complete (there are 3 wagons, one, 5) and end up disappearing.
I think I remember the same thing happened with your "Snooper" mod + "Real Time".
I'm going to test it.

Edit.- Found: nothing else start savegame without AVO mod, the trains have returned charge, everything ok.
Use _Advanced Vehicle Options AVO (Industries DLC ready)_
https://steamcommunity.com/sharedfiles/filedetails/?id=1548831935
There is another AVO mod, I am going to try it.

**Comment by benzoll37** [comment]
There is definitely conflict with both AVO and _Cargo Train_. In game there is no error message or warning.
_Advanced Vehicle Options AVO (Industries DLC ready)_  -I use this-
_Advanced Vehicle Options (AVO)_

If it helps, Output_log:
https://gist.github.com/benzoll37/f99da383837eb0978481e8b081df2cef

**Comment by dymanoid** [comment]
Thank you for testing! I updated the description on Steam and will investigate the issue. Probably the AVO mod will need to update to become compatible.

**Comment by CityGecko** [comment]
1.9.0 has received code for compatibility. I would appreciate some feedback on behaviour. I added MV recently to a savegame of mine and checked the cargo train spawning. There was no unexpected behaviour, trains show correct with all carriages and engine, custom ones and vanilla.

**Comment by dymanoid** [comment]
@CityGecko, yes, the AVO v1.9 is now compatible with More Vehicles.
I'm closing this issue.
