### ISSUE TITLE
Incompatibility with Improved Public Transport 2

### ISSUE THREAD

**Issue by mgrantdev** [dymanoid/MoreVehicles#3]
Until today, I have been unable to get More Vehicles to work on my map with 275k cims (the mod itself worked, but the game threw an "Array Out of Index" exception every other second). However, I started disabling/removing mods that altered the traffic simulation to find the culprit and I narrowed it down to BloodyPenguin's Improved Public Transport 2. Some more testing confirmed that when IPT2 is disabled, More Vehicles works just fine, but when IPT2 and More Vehicles are both enabled, the error persists. 

I'm not sure if More Vehicles is _actually_ the cause of the error, or if anyone else is having this issue, but Improved Public Transport 2 certainly seems to be causing some sort of issue for me.

**Comment by dymanoid** [comment]
Unfortunately, all incompatibilities need to be fixed on the other side. **More Vehicles** changes the base game infrastructure, so other mods need to take that into account.

**Comment by dymanoid** [comment]
Tagging @bloodypenguin.

**Comment by mgrantdev** [comment]
In the meantime, I've found that Klyte's Transport Lines Manager **does work** with More Vehicles. Not sure if BloodyPenguin will replace IPT2 anytime soon, so Transport Lines Manager is a suitable replacement for the time being. As always, thank you for your hard work!

**Comment by dymanoid** [comment]
Thanks for excessive testing!

**Comment by Sipke82** [comment]
I believe the IPT2 is now updated to be made compatible.
