### ISSUE TITLE
IsWorkshopMode + Offline mode causing problems?

### ISSUE THREAD

**Issue by Sikandar101** [dymanoid/MoreVehicles#4]
Hey, I'm very much a novice here but, if I understand correctly, there is an IsWorkshopMode check which may be causing myself and others problems when trying to use this mod offline. If that is the case, might I suggest removing it? Apologies if I have misunderstood the code.

**Comment by dymanoid** [comment]
This mod is using the Workshop to obtain other installed mods. For example, it checks if TM:PE stable is installed.
The mod is published in the Steam Workshop, so there should be no possibilities running it in the offline mode too.
