### ISSUE TITLE
Mod not working on non steam versions

### ISSUE THREAD

**Issue by chorong761** [dymanoid/MoreVehicles#7]
I am trying to manually install this mod on my EA Origin version of the game, but the mod shows up under content manager but doesn't look like it is working (after running the city for a while, I don't more traffic or improvement on industry no goods). 

I know that those show limit mods would not show the new limit, so i cannot verify if the mod is working or not.

**Comment by dymanoid** [comment]
This is intended. The mod needs to check whether incompatible mods are running. This check is done via the Steam ID of the incompatible mods.

**Comment by chorong761** [comment]
> This is intended. The mod needs to check whether incompatible mods are running. This check is done via the Steam ID of the incompatible mods.

I see, would it be possible to have a version of the mod that doesn't do an incompatibility check but used at the players risk?

**Comment by jackfood** [comment]
> > This is intended. The mod needs to check whether incompatible mods are running. This check is done via the Steam ID of the incompatible mods.
> 
> I see, would it be possible to have a version of the mod that doesn't do an incompatibility check but used at the players risk?

Possible by removing the Steam check and Compatibility checks. Email me chunghong2004@hotmail.com if you want an offline version of More Vehicles.

**Comment by maaslander81** [comment]
Hello, in 2021 if asked if you could make me an offline version and jackfood made one for me worked like a charm, can anyone make me a new one, i recently started playing again and upped my mods to the new version of the game but. My more vehicles buggs out the airport. 
If anyone can help out that would be awesome

Ps. jackfood removed steam check and compatibilty check.

**Comment by serrrgey05** [comment]
> Здравствуйте, в 2021 году, если бы вас спросили, можете ли вы сделать мне офлайн-версию, и jackfood сделал одну для меня, сработал как по волшебству, может ли кто-нибудь сделать меня новым, я недавно снова начал играть и повысил свои моды до новой версии игры, но. Мои машины выезжают из аэропорта. Если кто-то может помочь, это было бы здорово
> 
> Ps. jackfood убрал проверку пара и проверку совместимости.

Good time of day. Can you please share the offline version of the mod? or is it no longer relevant?
